vti_encoding:SR|utf8-nl
vti_timelastmodified:TW|18 Oct 2006 09:18:28 -0000
vti_author:SR|TRANDANG\\DANG
vti_modifiedby:SR|TRANDANG\\DANG
vti_nexttolasttimemodified:TW|18 Oct 2006 09:18:28 -0000
vti_timecreated:TR|09 Apr 2007 00:38:37 -0000
vti_lineageid:SR|{2C988519-0383-4533-B695-FFCA19BF018C}
vti_cacheddtm:TX|09 Apr 2007 00:38:38 -0000
vti_filesize:IR|26961
vti_extenderversion:SR|5.0.2.2623
vti_backlinkinfo:VX|
vti_syncwith_www.buudiencamau.com.vn\:80:TW|18 Oct 2006 09:18:28 -0000
vti_sourcecontrolversion:SX|V1
vti_sourcecontrolcookie:SX|fp_internal
