vti_encoding:SR|utf8-nl
vti_timelastmodified:TW|22 Mar 2006 01:09:44 -0000
vti_author:SR|TRANDANG\\DANG
vti_modifiedby:SR|TRANDANG\\DANG
vti_nexttolasttimemodified:TW|22 Mar 2006 01:09:44 -0000
vti_timecreated:TR|09 Apr 2007 00:38:37 -0000
vti_lineageid:SR|{F5B89451-A041-497F-AC54-97B54B434B83}
vti_cacheddtm:TX|09 Apr 2007 00:38:38 -0000
vti_filesize:IR|19921
vti_extenderversion:SR|5.0.2.2623
vti_backlinkinfo:VX|
vti_syncwith_www.buudiencamau.com.vn\:80:TW|22 Mar 2006 01:09:44 -0000
vti_sourcecontrolversion:SX|V1
vti_sourcecontrolcookie:SX|fp_internal
