vti_encoding:SR|utf8-nl
vti_timelastmodified:TW|19 Oct 2006 08:45:27 -0000
vti_author:SR|TRANDANG\\DANG
vti_modifiedby:SR|TRANDANG\\DANG
vti_nexttolasttimemodified:TW|19 Oct 2006 08:45:27 -0000
vti_timecreated:TR|09 Apr 2007 00:38:36 -0000
vti_lineageid:SR|{CD0864BB-FF28-4B85-BE92-B7460EE28036}
vti_cacheddtm:TX|09 Apr 2007 00:38:38 -0000
vti_filesize:IR|27313
vti_extenderversion:SR|5.0.2.2623
vti_backlinkinfo:VX|VietTool/code/noidung2.asp VietTool/noidung.asp VietTool/newsedit.asp VietTool/newsedit_SP(luu).asp VietTool/newsedit_SP(luu2).asp VietTool/script_tool/NewsEdit.asp VietTool/newsedit_SP.asp VietTool/traloi.asp VietTool/vanban.asp VietTool/code/noidung.asp VietTool/code/noidung03.asp
vti_syncwith_www.buudiencamau.com.vn\:80:TW|19 Oct 2006 08:45:27 -0000
vti_sourcecontrolversion:SX|V1
vti_sourcecontrolcookie:SX|fp_internal
